#!/bin/bash

echo '{"port_password": {"2333": "12345678", "2334": "12345678"}, "method": "aes-256-cfb", "timeout": 300, "server": "0.0.0.0"}' > /etc/shadowsocks.json
git clone https://github.com/miojizzy/auto_ssserver.git > /tmp/init_log 2>&1
cd auto_ssserver && ./setup.sh si 
touch testfile

