#!/bin/bash

mkdir /data
cd /data
cat > config.json <<EOF
{"port_password": {"2333": "12345678", "2334": "12345678"}, "method": "aes-256-cfb", "timeout": 300, "server": "0.0.0.0"}
EOF
git clone -b develop https://github.com/miojizzy/auto_ssserver.git > git_log 2>&1
cd auto_ssserver && ./setup.sh osi 
touch testfile

